#pragma once

static const char *wifi_config_html =
"<!DOCTYPE html>"
"<html lang='zh-CN'>"
"<head>"
"<meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>ESP32 控制台</title>"

"<style>"
"body{margin:0;font-family:Arial;background:#f5f6fa;}"
".header{background:#2d8cf0;color:#fff;padding:12px;text-align:center;font-size:18px;}"
".tabs{display:flex;background:#fff;border-bottom:1px solid #ddd;}"
".tab{flex:1;text-align:center;padding:12px 0;cursor:pointer;color:#555;}"
".tab.active{color:#2d8cf0;border-bottom:2px solid #2d8cf0;font-weight:bold;}"
".content{padding:16px;}"
".page{display:none;}"
".page.active{display:block;}"
".card{background:#fff;border-radius:6px;padding:14px;margin-bottom:14px;"
"box-shadow:0 1px 4px rgba(0,0,0,0.1);}"
".row{margin-top:10px;}"
"input,select{width:100%;padding:6px;margin-top:6px;}"
"button{background:#2d8cf0;color:#fff;border:none;"
"padding:8px 14px;border-radius:4px;font-size:14px;margin-top:6px;}"
".gap{height:8px;}"
"</style>"
"</head>"

"<body>"

"<div class='header'>ESP32 控制系统</div>"

"<div class='tabs'>"
"<div class='tab active' onclick='showPage(0)'>系统配置</div>"
"<div class='tab' onclick='showPage(1)'>半自动</div>"
"<div class='tab' onclick='showPage(2)'>全自动</div>"
"<div class='tab' onclick='showPage(3)'>妇科</div>"
"</div>"

"<div class='content'>"

/* ================= 系统配置 ================= */
"<div class='page active'>"
"<div class='card'>"
"<h3>WiFi 配置</h3>"
"<button onclick='scanWifi()'>扫描 WiFi</button>"
"<select id='ssid'></select>"
"<input id='pwd' type='password' placeholder='WiFi 密码'>"
"<button onclick='saveWifi()'>保存并连接</button>"
"</div>"
"</div>"

/* ================= 半自动 ================= */
"<div class='page'>"
"<div class='card'>"
"<h3>UC50</h3>"
"<div class='row'>"
"<button onclick=\"getFw('UC50','fw_uc50')\">固件获取</button>"
"<input id='fw_uc50' readonly placeholder='当前固件名'>"
"</div>"
"<div class='row'>"
"<select id='data_uc50'></select>"
"<button onclick=\"upload('UC50','data_uc50')\">数据上传</button>"
"</div>"
"</div>"

"<div class='card'>"
"<h3>UC280</h3>"
"<div class='row'>"
"<button onclick=\"getFw('UC280','fw_uc280')\">固件获取</button>"
"<input id='fw_uc280' readonly placeholder='当前固件名'>"
"</div>"
"<div class='row'>"
"<select id='data_uc280'></select>"
"<button onclick=\"upload('UC280','data_uc280')\">数据上传</button>"
"</div>"
"</div>"

"<div class='card'>"
"<h3>EM100</h3>"
"<div class='row'>"
"<button onclick=\"getFw('EM100','fw_em100')\">固件获取</button>"
"<input id='fw_em100' readonly placeholder='当前固件名'>"
"</div>"
"<div class='row'>"
"<select id='data_em100'></select>"
"<button onclick=\"upload('EM100','data_em100')\">数据上传</button>"
"</div>"
"</div>"
"</div>"

/* ================= 全自动 ================= */
"<div class='page'>"
"<div class='card'>"
"<h3>UC1600</h3>"
"<div class='row'>"
"<button onclick=\"getFw('UC1600','fw_uc1600')\">固件获取</button>"
"<input id='fw_uc1600' readonly placeholder='当前固件名'>"
"</div>"
"<div class='row'>"
"<select id='data_uc1600'></select>"
"<button onclick=\"upload('UC1600','data_uc1600')\">数据上传</button>"
"</div>"
"</div>"

"<div class='card'>"
"<h3>UC1800</h3>"
"<div class='row'>"
"<button onclick=\"getFw('UC1800','fw_uc1800')\">固件获取</button>"
"<input id='fw_uc1800' readonly placeholder='当前固件名'>"
"</div>"
"<div class='row'>"
"<select id='data_uc1800'></select>"
"<button onclick=\"upload('UC1800','data_uc1800')\">数据上传</button>"
"</div>"
"</div>"
"</div>"

/* ================= 妇科 ================= */
"<div class='page'>"
"<div class='card'>"
"<h3>SL1000</h3>"
"<div class='row'>"
"<button onclick=\"getFw('SL1000','fw_sl1000')\">固件获取</button>"
"<input id='fw_sl1000' readonly placeholder='当前固件名'>"
"</div>"
"<div class='row'>"
"<select id='data_sl1000'></select>"
"<button onclick=\"upload('SL1000','data_sl1000')\">数据上传</button>"
"</div>"
"</div>"
"</div>"

"</div>"

/* ================= JS ================= */
"<script>"
"function showPage(i){"
"let t=document.querySelectorAll('.tab');"
"let p=document.querySelectorAll('.page');"
"t.forEach(e=>e.classList.remove('active'));"
"p.forEach(e=>e.classList.remove('active'));"
"t[i].classList.add('active');p[i].classList.add('active');}"
"function scanWifi(){fetch('/api/wifi/scan').then(r=>r.json()).then(d=>{"
"let s=document.getElementById('ssid');s.innerHTML='';"
"d.forEach(n=>{let o=document.createElement('option');o.value=n;o.text=n;s.appendChild(o);});});}"
"function saveWifi(){fetch('/api/wifi/config',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({ssid:ssid.value,password:pwd.value})});}"
"function getFw(m,id){fetch('/api/firmware/get?model='+m).then(r=>r.text()).then(n=>{document.getElementById(id).value=n;});}"
"function upload(m,id){let f=document.getElementById(id).value;"
"fetch('/api/data/upload?model='+m+'&file='+f);}"
"</script>"

"</body></html>";
