#pragma once

static const char *wifi_config_html =
"<!DOCTYPE html>"
"<html lang='zh-CN'>"
"<head>"
"<meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>ESP32 设备管理控制台</title>"
"<style>"
"body{margin:0;font-family:Arial;background:#f2f4f8;}"
".header{background:#2d8cf0;color:#fff;padding:14px;text-align:center;font-size:18px;}"
".tabs{display:flex;background:#fff;border-bottom:1px solid #ddd;}"
".tab{flex:1;text-align:center;padding:12px 0;cursor:pointer;color:#555;}"
".tab.active{color:#2d8cf0;border-bottom:3px solid #2d8cf0;font-weight:bold;}"
".content{padding:16px;max-width:820px;margin:auto;}"
".page{display:none;}"
".page.active{display:block;}"
".card{background:#fff;border-radius:8px;padding:16px;margin-bottom:16px;box-shadow:0 2px 6px rgba(0,0,0,0.08);}"
".card h3{margin:0 0 10px;font-size:16px;border-left:4px solid #2d8cf0;padding-left:8px;}"
"label{display:block;margin-top:12px;font-size:14px;font-weight:500;}"
"input,select{width:100%;padding:8px;margin-top:6px;border-radius:4px;border:1px solid #ccc;font-size:14px;}"
".tip{font-size:12px;color:#888;margin-top:4px;line-height:1.5;}"
".btn{margin-top:14px;padding:8px 16px;border:none;border-radius:4px;font-size:14px;cursor:pointer;}"
".btn-primary{background:#2d8cf0;color:#fff;}"
".btn-success{background:#19be6b;color:#fff;}"
".btn-outline{background:#fff;border:1px solid #2d8cf0;color:#2d8cf0;width:100%;margin-top:10px;}"
".inline{display:flex;gap:12px;flex-wrap:wrap;align-items:end;}"
".inline>div{flex:1;min-width:220px;}"
"</style>"
"</head>"
"<body>"
"<div class='header'>ESP32 设备管理控制台</div>"
"<div class='tabs'>"
"<div class='tab active' onclick='showPage(0)'>系统配置</div>"
"<div class='tab' onclick='showPage(1)'>仪器配置</div>"
"</div>"
"<div class='content'>"
"<div class='page active'>"
"<div class='card'>"
"<h3>WiFi 设置</h3>"
"<button class='btn btn-primary' onclick='scanWifi()'>扫描附近 WiFi</button>"
"<label>WiFi 网络</label>"
"<select id='wifiList'></select>"
"<label>WiFi 密码</label>"
"<input type='password' id='wifiPwd'>"
"<button class='btn btn-success' onclick='connectWifi()'>保存并连接</button>"
"</div>"
"<div class='card'>"
"<h3>设备信息</h3>"
"<p>软件版本号：V1.0.0</p>"
"<p>硬件版本号：HW-A1</p>"
"<button class='btn btn-outline' onclick='triggerQuickUpdate()'>软件更新</button>"
"</div>"
"</div>"
"<div class='page'>"
"<div class='card'>"
"<h3>产品线选择</h3>"
"<label>产品线 (自动同步服务器)</label>"
"<select id='productLine' onchange='updateUI()'></select>"
"<div id='modelBox'>"
"<label>平台</label>"
"<select id='model' onchange='fetchVersions()'></select>"
"</div>"
"</div>"
"<div class='card'>"
"<h3>固件与数据配置</h3>"
"<label>下载固件版本号</label>"
"<select id='otaFirmwareVersion'></select>"
"<div class='tip'>选择平台后自动获取版本列表</div>"
"<h3 style='margin-top:18px'>数据上传配置</h3>"
"<label>本地文件名称</label>"
"<div class='inline'>"
"<div><select id='localFileSelect'></select></div>"
"<div style='flex:0'><button class='btn btn-primary' onclick='loadUsbFiles()'>刷新文件列表</button></div>"
"</div>"
"<div class='tip'>显示U盘中的文件列表</div>"
"<label>上传文件名称</label>"
"<input id='uploadServerInput' placeholder='如：upload_20240208.dat'>"
"<button class='btn btn-success' onclick='saveInstrumentConfig()'>保存配置</button>"
"</div>"
"</div>"
"</div>"
"<script>"
"let g_serverProducts = [];"
"function showPage(i){"
"document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));"
"document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));"
"document.querySelectorAll('.tab')[i].classList.add('active');"
"document.querySelectorAll('.page')[i].classList.add('active');"
"}"

"async function updateUI(){"
"const pl = document.getElementById('productLine');"
"const productId = pl.options[pl.selectedIndex].getAttribute('data-id');"
"const modelSelect = document.getElementById('model');"
"modelSelect.innerHTML = '<option>加载中...</option>';"
"try{"
"const res = await fetch('/api/get_platforms?id=' + productId + '&t=' + Date.now());"
"const json = await res.json();"
"modelSelect.innerHTML = '';"
"if(json.code === 0 && json.data.length > 0){"
"json.data.forEach(p => {"
"let o = document.createElement('option'); o.text = p.name; o.value = p.id; modelSelect.add(o);"
"});"
"await fetchVersions();"
"}else{"
"modelSelect.innerHTML = '<option value=\"\">无平台信息</option>';"
"}"
"}catch(e){ modelSelect.innerHTML = '<option>获取失败</option>'; }"
"}"

"async function fetchVersions(){"
"const modelSelect = document.getElementById('model');"
"const platformId = modelSelect.value;"
"const vSelect = document.getElementById('otaFirmwareVersion');"
"if(!platformId) return;"
"vSelect.innerHTML = '<option>查询中...</option>';"
"try{"
"const res = await fetch('/api/get_versions?id=' + platformId + '&t=' + Date.now());"
"const json = await res.json();"
"vSelect.innerHTML = '';"
"if(json.code === 0 && json.data.length > 0){"
"json.data.forEach(v => {"
"let o = document.createElement('option'); "
"const verStr = v.version || v.name || '';"
"o.text = verStr; o.value = verStr; vSelect.add(o);"
"});"
"}else{"
"let o = document.createElement('option'); o.text = '无可用版本'; vSelect.add(o);"
"}"
"}catch(e){ vSelect.innerHTML = '<option>查询失败</option>'; }"
"}"

"async function fetchProductList(){"
"try{"
"const res = await fetch('/api/get_product_list?t='+Date.now());"
"const json = await res.json();"
"if(json.code === 0){"
"g_serverProducts = json.data;"
"const pl = document.getElementById('productLine');"
"pl.innerHTML = '';"
"g_serverProducts.forEach(p => {"
"let o = document.createElement('option');"
"o.text = p.name; o.value = p.code;"
"o.setAttribute('data-id', p.id);"
"pl.add(o);"
"});"
"if(g_serverProducts.length > 0) await updateUI();"
"}"
"}catch(e){ console.error('获取产品失败', e); }"
"}"

"async function loadUsbFiles(){"
"try{"
"const response=await fetch('/usb_files?t='+Date.now());"
"const data=await response.json();"
"const select=document.getElementById('localFileSelect');"
"select.innerHTML='';"
"if(!data || data.length===0){"
"let o=document.createElement('option'); o.text='未发现文件'; select.add(o);"
"return;"
"}"
"data.forEach(file=>{"
"let o=document.createElement('option'); o.text=file; o.value=file; select.add(o);"
"});"
"}catch(err){ alert('读取U盘失败'); }"
"}"

"window.onload = async function(){"
"await fetchProductList();"
"try{"
"const wifiResp = await fetch('/get_wifi_info?t=' + Date.now());"
"if(wifiResp.ok){"
"const wifiData = await wifiResp.json();"
"if(wifiData.ssid){"
"document.getElementById('wifiPwd').value = wifiData.password || '';"
"let ws = document.getElementById('wifiList');"
"let o = document.createElement('option');"
"o.text = wifiData.ssid + ' (已连接)'; o.value = wifiData.ssid;"
"ws.add(o); ws.value = wifiData.ssid;"
"}"
"}"
"}catch(e){}"
"try{"
"const instResp = await fetch('/get_instrument_config?t=' + Date.now());"
"if(instResp.ok){"
"const cfg = await instResp.json();"
"if(cfg.product_code) document.getElementById('productLine').value = cfg.product_code;"
"await updateUI();"
"if(cfg.platform_code) document.getElementById('model').value = cfg.platform_code;"
"await fetchVersions();"
"if(cfg.firmware_version) document.getElementById('otaFirmwareVersion').value = cfg.firmware_version;"
"document.getElementById('uploadServerInput').value = cfg.uploadServer || '';"
"}"
"}catch(e){}"
"await loadUsbFiles();"
"};"

"function scanWifi(){"
"fetch('/scan?t='+Date.now()).then(r=>r.json()).then(data=>{"
"const s=document.getElementById('wifiList'); s.innerHTML='';"
"data.forEach(i=>{ let o=document.createElement('option'); o.text=i.ssid+' ('+i.rssi+' dBm)'; o.value=i.ssid; s.add(o); });"
"}).catch(()=>alert('扫描失败'));"
"}"

"function connectWifi(){"
"const s=document.getElementById('wifiList').value; const p=document.getElementById('wifiPwd').value;"
"fetch('/connect_wifi',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ssid:s,password:p})})"
".then(r=>r.text()).then(d=>alert(d));"
"}"
"async function triggerQuickUpdate() {"
"const mod = document.getElementById('model');"
"const pl = document.getElementById('productLine');"
"const pId = mod.value;" // 获取选中的平台 ID (数字)
"if(!pId || pId.includes('加载') || pId.includes('无')){ alert('请先选择有效的平台'); return; }"
"if(!confirm('是否获取最新固件对本机进行一键升级？')) return;"
"try {"
"const res = await fetch('/save_instrument_config', {"
"method: 'POST',"
"headers: {'Content-Type': 'application/json'},"
"body: JSON.stringify({"
"platform_id: parseInt(pId)," // 传入真实的平台 ID
"product_code: pl.value,"      // 传入当前产品线 code
"platform_code: mod.options[mod.selectedIndex].text," // 传入平台名称
"firmware_version: 'latest'"   // 触发后端一键升级逻辑的标识
"})"
"});"
"const d = await res.text();"
"alert('指令已下发: ' + d);"
"} catch (e) { alert('网络请求失败'); }"
"}"

"function saveInstrumentConfig(){"
"const pl = document.getElementById('productLine');"
"const mod = document.getElementById('model');"
"const pId = mod.value;"
"const pName = mod.options[mod.selectedIndex].text;"
"const pCode = pl.value;"
"const ver = document.getElementById('otaFirmwareVersion').value;"
"const lFile = document.getElementById('localFileSelect').value;"
"const uSvr = document.getElementById('uploadServerInput').value.trim();"

"fetch('/save_instrument_config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({"
"platform_id: pId,"
"platform_name: pName,"
"product_code: pCode,"
"firmware_version: ver,"
"localFile: lFile,"
"uploadServer: uSvr"
"})})"
".then(r=>r.text()).then(d=>alert(d));"
"}"
"</script></body></html>";