#pragma once
#define FW_VERSION "V1.0.2" // 以后只需修改这里
#define HW_VERSION "HW-A1"
static const char *wifi_config_html =
"<!DOCTYPE html>"
"<html lang='zh-CN'>"
"<head>"
"<meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>ESP32 设备管理控制台</title>"
"<style>"
"body{margin:0;font-family:Arial;background:#f2f4f8;}"
".header{background:#2d8cf0;color:#fff;padding:14px;text-align:center;font-size:18px;}"
".tabs{display:flex;background:#fff;border-bottom:1px solid #ddd;}"
".tab{flex:1;text-align:center;padding:12px 0;cursor:pointer;color:#555;}"
".tab.active{color:#2d8cf0;border-bottom:3px solid #2d8cf0;font-weight:bold;}"
".content{padding:16px;max-width:820px;margin:auto;}"
".page{display:none;}"
".page.active{display:block;}"
".card{background:#fff;border-radius:8px;padding:16px;margin-bottom:16px;box-shadow:0 2px 6px rgba(0,0,0,0.08);}"
".card h3{margin:0 0 10px;font-size:16px;border-left:4px solid #2d8cf0;padding-left:8px;}"
"label{display:block;margin-top:12px;font-size:14px;font-weight:500;}"
"input,select{width:100%%;padding:8px;margin-top:6px;border-radius:4px;border:1px solid #ccc;font-size:14px;}"
".tip{font-size:12px;color:#888;margin-top:4px;line-height:1.5;}"
".btn{margin-top:14px;padding:8px 16px;border:none;border-radius:4px;font-size:14px;cursor:pointer;}"
".btn-primary{background:#2d8cf0;color:#fff;}"
".btn-success{background:#19be6b;color:#fff;}"
".btn-outline{background:#fff;border:1px solid #2d8cf0;color:#2d8cf0;width:100%%;margin-top:10px;}"
".inline{display:flex;gap:12px;flex-wrap:wrap;align-items:end;}"
".inline>div{flex:1;min-width:220px;}"
"</style>"
"</head>"
"<body>"
"<div class='header'>ESP32 设备管理控制台</div>"
"<div class='tabs'>"
"<div class='tab active' onclick='showPage(0)'>系统配置</div>"
"<div class='tab' onclick='showPage(1)'>仪器配置</div>"
"</div>"
"<div class='content'>"
"<div class='page active'>"
"<div class='card'>"
"<h3>WiFi 设置</h3>"
"<button class='btn btn-primary' onclick='scanWifi()'>扫描附近 WiFi</button>"
"<label>WiFi 网络</label>"
"<select id='wifiList'></select>"
"<label>WiFi 密码</label>"
"<input type='password' id='wifiPwd'>"
"<button class='btn btn-success' onclick='connectWifi()'>保存并连接</button>"
"</div>"
"<div class='card'>"
"<h3>设备信息</h3>"
"<p>软件版本号：" FW_VERSION "</p>"
"<p>硬件版本号：" HW_VERSION "</p>"
/* 修改点 1：完全复用 <p> 标签，确保字号字体完全一致，内部嵌入原生 Checkbox 开关 */
"<p><label style='display:inline;font-weight:normal;font-size:inherit;margin:0;'><input type='checkbox' id='usbBootToggle' onchange='toggleUsbBoot(this)' style='width:auto;margin:0 6px 0 0;vertical-align:middle;'>启用U盘功能</label></p>"
"<button class='btn btn-outline' onclick='triggerQuickUpdate()'>软件更新</button>"
"</div>"
"</div>"
"<div class='page'>"
"<div class='card'>"
"<h3>产品线选择</h3>"
"<label>产品线 (自动同步服务器)</label>"
"<div class='inline'>"
"<div><select id='productLine' onchange='updateUI()'></select></div>"
"<div style='flex:0'><button class='btn btn-primary' onclick='fetchProductList()' style='white-space:nowrap'>刷新列表</button></div>"
"</div>"
"<div class='tip'>如果产品列表为空，请重启设备同步数据</div>"
"<div id='modelBox'>"
"<label>平台</label>"
"<select id='model' onchange='fetchVersions()'></select>"
"</div>"
"</div>"
"<div class='card'>"
"<h3>固件与数据配置</h3>"
"<label>下载固件版本号</label>"
"<select id='otaFirmwareVersion'></select>"
"<div class='tip'>选择平台后自动获取版本列表</div>"
"<h3 style='margin-top:18px'>数据上传配置</h3>"
"<label>本地文件名称</label>"
"<div class='inline'>"
"<div><select id='localFileSelect'></select></div>"
"<div style='flex:0'><button class='btn btn-primary' onclick='loadUsbFiles()'>刷新文件列表</button></div>"
"</div>"
"<div class='tip'>显示U盘中的文件列表</div>"
"<label>上传文件名称</label>"
"<input id='uploadServerInput' placeholder='如：upload_20240208.dat'>"
"<button class='btn btn-success' onclick='saveInstrumentConfig()'>保存配置</button>"
"</div>"
"</div>"
"</div>"
"<script>"
"let g_serverProducts = [];"
"function showPage(i){"
"document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));"
"document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));"
"document.querySelectorAll('.tab')[i].classList.add('active');"
"document.querySelectorAll('.page')[i].classList.add('active');"
"}"

"async function updateUI(){"
"const pl = document.getElementById('productLine');"
"const selectedOption = pl.options[pl.selectedIndex];"
"if(!selectedOption){"
"document.getElementById('modelBox').innerHTML = '<div class=\"tip\" style=\"color:red\">请先同步产品列表（重启设备）或从下拉列表选择产品</div>';"
"return;"
"}"
"const productId = selectedOption.getAttribute('data-id');"
"if(!productId){"
"document.getElementById('modelBox').innerHTML = '<div class=\"tip\" style=\"color:red\">产品列表数据不完整，请重启设备同步</div>';"
"return;"
"}"
"const modelSelect = document.getElementById('model');"
"modelSelect.innerHTML = '<option>加载中...</option>';"
"try{"
"const res = await fetch('/api/get_platforms?id=' + productId + '&t=' + Date.now());"
"const json = await res.json();"
"modelSelect.innerHTML = '';"
"if(json.code === 0 && json.data.length > 0){"
"json.data.forEach(p => {"
"let o = document.createElement('option'); o.text = p.name; o.value = p.id; modelSelect.add(o);"
"});"
"await fetchVersions();"
"}else{"
"modelSelect.innerHTML = '<option value=\"\">无平台信息</option>';"
"}"
"}catch(e){ console.error('updateUI error:', e); modelSelect.innerHTML = '<option>获取失败(网络问题或产品未同步)</option>'; }"
"}"

"async function fetchVersions(){"
"const modelSelect = document.getElementById('model');"
"const platformId = modelSelect.value;"
"const vSelect = document.getElementById('otaFirmwareVersion');"
"if(!platformId) return;"
"vSelect.innerHTML = '<option>查询中...</option>';"
"try{"
"const res = await fetch('/api/get_versions?id=' + platformId + '&t=' + Date.now());"
"const json = await res.json();"
"vSelect.innerHTML = '';"
"if(json.code === 0 && json.data.length > 0){"
"json.data.forEach(v => {"
"let o = document.createElement('option'); "
"const verStr = v.version || v.name || '';"
"o.text = verStr; o.value = verStr; vSelect.add(o);"
"});"
"}else{"
"let o = document.createElement('option'); o.text = '无可用版本'; vSelect.add(o);"
"}"
"}catch(e){ vSelect.innerHTML = '<option>查询失败</option>'; }"
"}"

"async function fetchProductList(){"
"try{"
"const res = await fetch('/api/get_product_list?t='+Date.now());"
"const json = await res.json();"
"if(json.code === 0){"
"g_serverProducts = json.data;"
"const pl = document.getElementById('productLine');"
"pl.innerHTML = '';"
"g_serverProducts.forEach(p => {"
"let o = document.createElement('option');"
"o.text = p.name; o.value = p.code;"
"o.setAttribute('data-id', p.id);"
"pl.add(o);"
"});"
"if(g_serverProducts.length > 0) await updateUI();"
"}else{"
"console.warn('获取产品列表失败:', json);"
"}"
"}catch(e){ console.warn('获取产品列表失败(网络问题或数据未同步，请重启设备):', e); }"
"}"

"async function loadUsbFiles(){"
"try{"
"const response=await fetch('/usb_files?t='+Date.now());"
"const data=await response.json();"
"const select=document.getElementById('localFileSelect');"
"select.innerHTML='';"
"if(!data || data.length===0){"
"let o=document.createElement('option'); o.text='未发现文件'; select.add(o);"
"return;"
"}"
"data.forEach(file=>{"
"let o=document.createElement('option'); o.text=file; o.value=file; select.add(o);"
"});"
"}catch(err){ alert('读取U盘失败'); }"
"}"

"window.onload = async function(){"
"await fetchProductList();"
/* 修改点 2：初始化时获取并同步U盘启动开关的最新状态 */
"try{"
"const usbResp = await fetch('/get_usb_boot_config?t=' + Date.now());"
"if(usbResp.ok){"
"const usbData = await usbResp.json();"
"document.getElementById('usbBootToggle').checked = !!usbData.usb_boot_enabled;"
"}"
"}catch(e){}"

"try{"
"const wifiResp = await fetch('/get_wifi_info?t=' + Date.now());"
"if(wifiResp.ok){"
"const wifiData = await wifiResp.json();"
"if(wifiData.ssid){"
"document.getElementById('wifiPwd').value = wifiData.password || '';"
"let ws = document.getElementById('wifiList');"
"let o = document.createElement('option');"
"o.text = wifiData.ssid + ' (已连接)'; o.value = wifiData.ssid;"
"ws.add(o); ws.value = wifiData.ssid;"
"}"
"}"
"}catch(e){}"
"try{"
"const instResp = await fetch('/get_instrument_config?t=' + Date.now());"
"if(instResp.ok){"
"const cfg = await instResp.json();"
"const pl = document.getElementById('productLine');"
"if(cfg.product_code){"
"let option = pl.querySelector('option[value=\"' + cfg.product_code + '\"]');"
"if(!option && cfg.platform_name){"
"option = document.createElement('option');"
"option.value = cfg.product_code;"
"option.text = cfg.platform_name;"
"option.setAttribute('data-id', cfg.platform_id || '0');"
"pl.appendChild(option);"
"}"
"if(option) pl.value = cfg.product_code;"
"}"
"if(pl.options.length > 0) await updateUI();"
"const modelSelect = document.getElementById('model');"
"if(cfg.platform_id && cfg.platform_name){"
"const modelOpt = document.createElement('option');"
"modelOpt.value = cfg.platform_id;"
"modelOpt.text = cfg.platform_name;"
"modelSelect.innerHTML = '';"
"modelSelect.appendChild(modelOpt);"
"modelSelect.value = cfg.platform_id;"
"}"
"if(cfg.firmware_version){"
"const vSelect = document.getElementById('otaFirmwareVersion');"
"const verOpt = document.createElement('option');"
"verOpt.value = cfg.firmware_version;"
"verOpt.text = cfg.firmware_version;"
"vSelect.innerHTML = '';"
"vSelect.appendChild(verOpt);"
"vSelect.value = cfg.firmware_version;"
"}"
"document.getElementById('uploadServerInput').value = cfg.uploadServer || '';"
"}"
"}catch(e){ console.error('加载配置失败', e); }"
"await loadUsbFiles();"
"};"

"function scanWifi(){"
"fetch('/scan?t='+Date.now()).then(r=>r.json()).then(data=>{"
"const s=document.getElementById('wifiList'); s.innerHTML='';"
"data.forEach(i=>{ let o=document.createElement('option'); o.text=i.ssid+' ('+i.rssi+' dBm)'; o.value=i.ssid; s.add(o); });"
"}).catch(()=>alert('扫描失败'));"
"}"

"function connectWifi(){"
"const s=document.getElementById('wifiList').value; const p=document.getElementById('wifiPwd').value;"
"fetch('/connect_wifi',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ssid:s,password:p})})"
".then(r=>r.text()).then(d=>alert(d));"
"}"

/* 修改点 3：增加下发状态变化的 POST 请求函数 */
"function toggleUsbBoot(cb){"
"fetch('/api/usb_control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({usb_boot_enabled:cb.checked})})"
".then(r=>r.text()).then(d=>{"
"console.log('U盘启动配置更新成功:', d);"
"}).catch(()=>{"
"alert('同步失败，请检查网络');"
"cb.checked = !cb.checked;"
"});"
"}"

"async function triggerQuickUpdate() {"
"const mod = document.getElementById('model');"
"const pl = document.getElementById('productLine');"
"const pId = mod.value;"
"if(!pId || pId.includes('加载') || pId.includes('无')){ alert('请先选择有效的平台'); return; }"
"if(!confirm('是否获取最新固件对本机进行一键升级？')) return;"
"try {"
"const res = await fetch('/do_update', {"
"method: 'POST',"
"headers: {'Content-Type': 'application/json'},"
"body: JSON.stringify({"
"platform_id: parseInt(pId),"
"product_code: pl.value,"
"platform_code: mod.options[mod.selectedIndex].text,"
"firmware_version: 'latest'"
"})"
"});"
"const d = await res.text();"
"alert('指令已下发: ' + d);"
"} catch (e) { alert('网络请求失败'); }"
"}"

"function saveInstrumentConfig(){"
"const pl = document.getElementById('productLine');"
"const mod = document.getElementById('model');"
"const pId = mod.value;"
"const pName = mod.options[mod.selectedIndex].text;"
"const pCode = pl.value;"
"const ver = document.getElementById('otaFirmwareVersion').value;"
"const lFile = document.getElementById('localFileSelect').value;"
"const uSvr = document.getElementById('uploadServerInput').value.trim();"

"fetch('/save_instrument_config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({"
"platform_id: pId,"
"platform_name: pName,"
"product_code: pCode,"
"firmware_version: ver,"
"localFile: lFile,"
"uploadServer: uSvr"
"})})"
".then(r=>r.text()).then(d=>alert(d));"
"}"
"</script></body></html>";